# playbooks/show_config.yml
---
- name: Show current configuration of network devices
  hosts: Routers
  gather_facts: false
  connection: network_cli
  
  vars:
    output_dir: ../../sources/show_config_outputs/

  roles:
    - show_config
